### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by alexreg** [murarth/rusti#96] opened 2017-12-01 00:42 UTC
This looks like a great project, though unfortunately it's well out-of-date, and could do with updates for the latest Rust (stable and nightly). Any chance of this happening?

**Comment by murarth** [comment] 2017-12-01 00:57
As described in issue #86, the rustc API that was used to compile code in memory is no longer available. rusti cannot be updated for a new version of Rust until a new API exists to fill this role.

(Closing as duplicate of #86.)

**Closed by murarth** 2017-12-01 00:57 UTC

**Comment by softprops** [comment] 2017-12-01 03:55
:/
