### ISSUE TITLE
LLVM ERROR: Program used external function '___morestack_addr' which could not be resolved!

### ISSUE THREAD

**Issue by yann-ledu** [murarth/rusti#17] opened 2015-03-06 22:37 UTC
This is what I get whatever I type.

**Comment by murarth** [comment] 2015-03-06 22:44
This appears to be a duplicate of #14 (which shouldn't have been closed). Are you also using OS X?

**Comment by yann-ledu** [comment] 2015-03-06 22:57
Yes

**Comment by murarth** [comment] 2015-03-06 23:12
Okay, closing this in favor of the aforementioned issue, which I've reopened.

**Closed by murarth** 2015-03-06 23:12 UTC
