### ISSUE TITLE
compiler error with Rust 1.0 stable

### ISSUE THREAD

**Issue by bluealert** [murarth/rusti#30] opened 2015-05-16 12:09 UTC
```
~/.cargo/registry/src/github.com-1ecc6299db9ec823/tempfile-0.2.0/src/lib.rs:1:1: 1:34 error: unstable feature
~/.cargo/registry/src/github.com-1ecc6299db9ec823/tempfile-0.2.0/src/lib.rs:1 #![feature(convert, from_raw_os)]
                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the stable release channel
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `tempfile`.

To learn more, run the command again with --verbose.

```

**Comment by murarth** [comment] 2015-05-16 15:07
Duplicate of #27

**Closed by murarth** 2015-05-16 15:07 UTC
